AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Team:
    Type: String
  Environment:
    Type: String
  Domain:
    Type: String
  Channel:
    Type: String
  Workspace:
    Type: String

Resources:
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Domain
          Value: ""
        - Key: Team
          Value: ""
      TopicName: "Demo_Notification"

  SlackBot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: demo-chatbot-dev
      IamRoleArn: !GetAtt SlackBotRole.Arn
      SlackChannelId: C03562Z43KQ
      SlackWorkspaceId: T035RALT1NV
      SnsTopicArns: 
        - !Ref NotificationTopic

  SlackBotRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SlackBotRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Events
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "events:*"
                Resource:
                  - "*"